# Generated by Django 5.2.1 on 2025-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0002_subject_alter_tutor_name_alter_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
