# Generated by Django 5.2.1 on 2025-05-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0003_alter_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titors', to='tutors_app.subject'),
        ),
    ]
