# Generated by Django 5.2.1 on 2025-06-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0006_remove_tutor_subject_tutor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='about_myself',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='city_or_online',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
