# Generated by Django 5.2.1 on 2025-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0007_tutor_about_myself_tutor_city_or_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='city_or_online',
            field=models.CharField(blank=True, default='online', max_length=100, null=True),
        ),
    ]
