# Generated by Django 5.2.1 on 2025-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0008_alter_tutor_city_or_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='id_tutor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
