# Generated by Django 5.2.1 on 2025-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0009_tutor_id_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='id_tutor',
            field=models.IntegerField(unique=True),
        ),
    ]
