# Generated by Django 5.2.1 on 2025-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0011_alter_tutor_id_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='city_or_online',
        ),
        migrations.AddField(
            model_name='tutor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id_tutor',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
