# Generated by Django 5.2.1 on 2025-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors_app', '0012_remove_tutor_city_or_online_tutor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
